server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true
    username: root
    password: 6388065025
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  issuer: auth-service
  access-token:
    secret: "myVeryLongAndSecureJwtSecretKeyForApiGatewayThatIsAtLeast32Characters"
    expiration-minutes: 120
  refresh-token:
    secret: "anotherVeryLongAndSecureJwtRefreshSecretKeyThatIsAtLeast32CharactersLongForSecurity"
    expiration-days: 30

app:
  super-admin:
    username: superadmin
    email: superadmin@example.com
    password: StrongPassword123!

services:
  user:
    base-url: http://localhost:8082

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web.client.RestTemplate: DEBUG
